### ISSUE TITLE
Using pump in csslint task throws exception. 

### ISSUE THREAD

**Issue by sonidodespacio** [lazd/gulp-csslint#56]
### I think it should work with pump. Am i wrong ?

```
var gulp = require('gulp');
var csslint = require('gulp-csslint');
```

//This task throws error.
```
gulp.task('lint-css', function() {
    pump([gulp.src('./app/css/styles.css'),
          csslint(),
          csslint.reporter(),
          onErrorHandler]);
});
```

```
gulp.task('lint-css', function() {
    gulp.src('./app/css/styles.css')
    .pipe(csslint())
	.pipe(csslint.reporter());
});
```

```
function onErrorHandler(error){
    if (error)
        console.log(error)
}
```

Error description throws using [pump](https://www.npmjs.com/package/pump).
```
[10:24:07] Using gulpfile ~\ex1.less\gulpfile.js
[10:24:07] Starting 'lint-css'...
[10:24:07] 'lint-css' errored after 8 ms
[10:24:07] TypeError: stream.on is not a function
    at destroyer (C:\ex1.less\node_modules\pump\index.js:23:10)
    at C:\ex1.less\node_modules\pump\index.js:67:12
    at Array.map (native)
    at pump (C:\ex1.less\node_modules\pump\index.js:64:26)
    at Gulp.<anonymous> (C:\ex1.less\gulpfile.js:63:5)
    at module.exports (C:\ex1.less\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\ex1.less\node_modules\gulp\node_modules\orchestrator\index.js:2
73:3)
    at Gulp.Orchestrator._runStep (C:\ex1.less\node_modules\gulp\node_modules\orchestrator\index.js:2
14:10)
    at Gulp.Orchestrator.start (C:\ex1.less\node_modules\gulp\node_modules\orchestrator\index.js:134:
8)
    at C:\User\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:129:20
```

**Comment by Spunkie** [comment]
This worked for me

```
gulp.task('lint-css', function(cb) {
	pump([
		gulp.src('./app/css/styles.css'),
		csslint(),
		csslint.reporter()
	], cb);
});
```

I'm pretty sure your pump issues are related to how you are calling the onErrorHandler function.

**Comment by sonidodespacio** [comment]
I think you are right I should have defined onErrorHandler like:
```
function onErrorHandler(callback, error){
    if (error)
        console.log(error)
}
```

But, either way it's not working. I tried:
```
gulp.task('csslint-pump', function(callback) {
  pump([gulp.src('./app/css/styles.css'),
          csslint(),
          csslint.reporter(),
          callback]);
});
```

And the result is the same.

**Comment by lazd** [comment]
@sonidodespacio you failed to add the callback correctly. You passed it at the end of the array being passed as the first argument to `pump([..., callback])` instead of passing it as the second argument to `pump([...], callback)`.

**Comment by sonidodespacio** [comment]
Thanks, it was my mistake. Totally true. Long hours.
